CREATE TABLE IF NOT EXISTS exams (
    id VARCHAR(255) PRIMARY KEY NOT NULL,
    patient_id VARCHAR(255) NOT NULL,
    exam_type VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);